name: mioamoreapp
description: A new Flutter project.
publish_to: "none"

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 2.0.1+7

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  flutter_riverpod: ^2.1.3
  hive_flutter: ^1.1.0
  flutter_easyloading: ^3.0.5
  hive: ^2.2.3
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0
  animations: ^2.0.7
  google_sign_in: ^6.0.0
  firebase_core: ^2.6.1
  firebase_auth: ^4.2.2
  cloud_firestore: ^4.4.2
  intl: ^0.18.0
  firebase_storage: ^11.0.13
  image_picker: ^1.0.1
  location: ^5.0.0
  emoji_picker_flutter: ^1.5.1
  custom_pop_up_menu: ^1.2.4
  auto_size_text: ^3.0.0
  geolocator: ^9.0.2
  http: ^0.13.5
  geocoding: ^2.0.5
  swipe_cards: ^2.0.0+1
  url_launcher: ^6.1.7
  sign_in_with_apple: ^5.0.0
  flutter_facebook_auth: ^5.0.7
  encrypt: ^5.0.1
  social_media_recorder: ^0.2.0
  voice_message_package: ^1.0.41
  google_mobile_ads: ^3.0.0
  firebase_messaging: ^14.2.4
  flutter_native_splash: ^2.2.17
  webview_flutter: ^4.0.1
  collection: ^1.16.0
  tutorial_coach_mark: ^1.2.4
  lottie: ^2.2.0
  video_player: ^2.5.1
  purchases_flutter: ^5.3.0
  change_app_package_name: ^1.1.0

  flutter_localizations:
    sdk: flutter

# dependency_overrides:
#   photo_view:
#     git:
#       url: https://github.com/bluefireteam/photo_view
#       ref: master
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/logos/
    - assets/json/
    - assets/json/lottie/

flutter_native_splash:
  background_image: "assets/images/splash.png"
  android_12: null
flutter_intl:
  enabled: true
